name: Check pull request source branch

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "$HEAD_REF" != "develop" ] && [ "$BASE_REF" = "master" ]; then
            echo "Pull requests to master are only allowed from develop."
            exit 1
          fi
